pg-irc/pathways-frontend

src/js/components/ServiceFiltersCard.js
src/js/components/ServiceFiltersDialog.js
src/js/components/ServiceMap.js
src/js/stores/index.js
src/js/stores/remote/ServiceProvidersStore.js
src/js/views/ServiceMapView.js

Closes #13
Closes pg-irc/pathways-backend#121

Rename LocationsStore to ServiceProvidersStore

---

src/components/questionnaire/questionnaire.tsx
src/locale/index.ts
src/selectors/__tests__/locale.test.ts
src/stores/__tests__/helpers/locale_helpers.ts
src/stores/__tests__/helpers/store_helpers.ts

Includes a ApplicationStoreBuilder helper.

Add tests for locale selectors

---

src/components/main/loader.tsx

Couldn't resist a quick bit of polish now that I've brushed up on my flex-box skills.

Loader displays a Spinner component, positioned in centre of available space

---

src/components/articles/article_detail.tsx
src/components/articles/article_detail_connected_component.tsx
src/components/articles/article_list.tsx
src/components/articles/article_list_item.tsx
src/components/related_articles/related_articles.tsx
src/components/related_tasks/related_tasks.tsx
src/components/tasks/task_detail.tsx
src/components/tasks/task_detail_connected_component.tsx
src/components/tasks/task_list.tsx
src/components/tasks/task_list_item.tsx
src/selectors/articles.ts
src/selectors/tasks.ts

@rasmus-storjohann-PG this piece of clean up didn't make it in to the last PR (forgot to push locally)

Issue #111 Create explicit types for tasks and article list items

---

README.md

As a condition for using Sauce Labs, they asked us to put a thank you on our repo. I just used the suggested markdown in the e mail that Cherrie got from them.
Shall we leave this in a branch until we've had a look at it and what it can do for us?

Add thank you to SauceLabs to README

---

app.json

The really important stuff is in the ticket comments on #170. There are a lot of moving parts and I'm afraid my notes may be a bit much but let me know if there are questions.

Issue #170 Update app.json to reflect new name

---

package.json
yarn.lock

@rasmus-storjohann-PG This should fix our questionnaire issues. We should take a closer look at this when we get the updated designs for the questionnaire.

Pin react-native-collapsible to fix questionnaire bug

---

src/application/index.tsx
src/components/main/main_component.tsx
src/components/main/main_connected_component.ts

Issue #61 Fix naming issues in the main component

---

src/application/__tests__/routing.test.ts
src/application/routing.ts
src/components/main/footer.tsx

Note: The point about making the bookmark button larger was done under #369 (pr #388)

Issue #377 Remove nav on questionnaire

---

package.json
src/components/about/about_component.tsx
src/components/questionnaire/questionnaire_component.tsx
src/components/services/service_list_item_component.tsx

We'll need to run a fresh `yarn extract-strings` as the string structure has changed in some of the about screen text in order to fix links that were previously not working in production. I've added `babel-core@^7.0.0-bridge.0` to make out extract command work again as per: https://lingui.js.org/ref/cli.html.

Issue #472 Address UX issues & fix Lingui CLI tools

---

app.json

Issue #496 Bump Android version

---

src/components/main/main_component.tsx
src/components/main/main_connected_component.ts
src/sagas/analytics/send_analytics_data.ts
src/stores/router_actions.ts

Note: This only currently tracks user language for screen views. We'll have to address events on a per event basis.

Issue #420 Google Analytics

---

src/application/styles.ts
src/components/tasks/task_detail_content_component.tsx

@rasmus-storjohann-PG  @bensinjin

Issue #429 Make link blue and add external link icon

---

src/api/index.ts
src/api/is_response_error.ts
src/async/error_types.ts
src/async/location.ts
src/components/services/service_list_error_component.tsx
src/json_schemas/validators.ts
src/sagas/services.ts
src/selectors/services/types.ts
src/stores/__tests__/helpers/services_helpers.ts
src/stores/__tests__/services.test.ts
src/stores/services/actions.ts
src/stores/services/index.ts
src/stores/services/types.ts

This PR cleans up some of the services code and provides a new error message when location fetch times out.

Issue #548 Location Android bug

---

src/fixtures/hard_coded/explore.ts

Still need to add missing Chinese Simplified titles.

Issue #554 add missing learn section titles

---

src/components/about/about_component.tsx

After adjusting this text we do now have a paragraph of untranslated text on the About screen. Please checkout and try this branch and you'll see what I'm referring to. The translation workflow has changed quite a bit so I'll need someone to weigh in on how we get this translation wherever it belongs.

Issue #700 Update About text

---

.env.example
App.js
package.json
src/@types/sentry-expo.d.ts
src/application/constants.ts
src/application/error_boundary.tsx
src/components/error_screens/ErrorScreenSwitcherComponent.tsx
src/components/services/service_list_component.tsx
src/validation/errors/sentry_messages.ts
yarn.lock

I messed up a rebase so had to open a new PR with pertinent commits cherry picked. The original discussions were over here: https://github.com/pg-irc/pathways-frontend/pull/884, I've addressed the PR comments there.
Testing instructions are here: https://github.com/pg-irc/pathways-frontend/issues/824 under the "Steps for QA using Sentry:" heading

Issue #824 more sentry tracking

---

bin/prepare_deploy.sh
src/validation/search/__tests__/validation.tests.ts
src/validation/search/schema.ts
src/validation/search/types.ts

Note: adjust your `ALGOLIA_SERVICES_INDEX` in your`.env` to what is seen here:
https://github.com/PeaceGeeksSociety/content/issues/726

Issue #967 missing phone and email to algolia search services

---

src/application/styles.ts
src/components/search/search_input_component.tsx
src/components/services/service_list_location_search_component.tsx

See https://github.com/pg-irc/pathways-frontend/issues/1078#issuecomment-610077155 - the requirements for this have changed a bit.

Issue #1078 Add disabled state to search buttons

---

bin/prepare_deploy.sh
src/components/explore/explore_detail_connected_component.ts
src/components/help/help_connected_component.tsx
src/components/services/service_list_connected_component.tsx
src/components/topics/topic_detail_connected_component.tsx
src/fixtures/hard_coded/tasks.ts
src/fixtures/types/topics.ts
src/selectors/__tests__/helpers/topic_helpers.ts
src/selectors/topics/select_help_topic_for_region.ts
src/selectors/topics/select_topic_by_id.ts
src/selectors/topics/select_topics_for_current_explore_section.ts
src/selectors/topics/to_selector_topic.ts
src/selectors/topics/types.ts
src/stores/__tests__/helpers/topics_helpers.ts

Issue 615 Add MB data to the app

---

bin/prepare_deploy.sh

Deploy script made invalid assumptions about the location of a file

Issue pg-irc/pathways-backend#634 Fix bug in deploy script
