bin/postinstall.sh, package-lock.json, package.json, src/application/store.ts, yarn.lock
Updated:
- Gives Remote Redux DevTools access to our Redux store state when running in debugging mode.
- Removes `remotedev-rn-debugger` as it was causing build step to hang and doesn't work consistently anyway.
There are via two methods to access Redux DevTools remotely:
- Visit http://remotedev.io/local/ : (should "just work" on iOS and Android simulators via https/port 443).
- The Redux DevTools Chrome Extension (only works with iOS simulator, likely because of port forwarding issues on Android's Simulator):
1. Enable remote debugging in Expo.
2. Open Chrome's dev inspector (on macOS: option+cmd+i).
3. Open the Redux tab press.
4. Start a remote session (ctrl+cmd+downarrow on macOS).
~Add devserver config back to store creation (lost in a rebase conflict resolution).~
~I just noticed …
=> Issue #69 Fix devtools server config

package.json
After some playing around, it seems to me that it doesn't understand the `\w` character set. When I replace that with a `.` then it manages to find and run all the tests. However, there is still a locale error that I don't understand. Here is the output:
```
$ yarn test
yarn run v1.7.0
$ yarn run build && yarn run jest
$ tsc
$ C:\Users\Theresa\PeaceGeeks\pathways-frontend\node_modules\.bin\jest
PASS  src\sagas\__tests__\fonts.test.ts (5.803s)
PASS  src\sagas\__tests__\locale.test.ts
● Console
console.error src\sagas\locale.ts:42
Failed to load current locale (43e96a8d-9bf8-4318-ae3b-7b4df3743940)
PASS  src\stores\__tests__\questionnaire.test.ts
PASS  src\stores\__tests__\tasks.test.ts
PASS  src\stores\__tests__\tasks_helpers.test.ts
PASS  src\selectors\__tests__\tasks.test.ts
PASS …
```
=> Issue #90 Fix jest regex

src/application/locale/__tests__/locale.test.ts, src/application/locale/index.ts, src/sagas/__tests__/locale.test.ts, src/sagas/locale.ts, src/stores/__tests__/locale.test.ts, src/stores/locale/index.ts
This tidies up the locale sagas implementation and fixes an issue on master where we get stuck on the loading screen (because the reducer currently handles the wrong action on initial startup (before a users locale preference has been persisted to database).
=> Issue #95 Seperate "set locale" and "load current locale" sagas

package-lock.json, package.json, yarn.lock
Updates to jsLingui 2.1.0 (which resolves the Babel dependency issue).
=> Update jsLingui to latest release (#99)

package.json, yarn.lock
This fixes the need for our forked version of the native-base library.
=> Issue #119 Upgrade native-base to 2.5.2

src/components/services/service.tsx, src/stores/__tests__/helpers/services_helpers.ts, src/stores/services/index.ts, src/stores/services/schemas.ts, src/stores/services/types.ts
This is some clean up around the address piece for task services. The goal here was to keep consistent with our already established pattern which maybe wasn't as obvious as it could be so I'm putting it here:
`request JSON from server -> validate JSON (throw if invalid) -> convert TS type representing valid JSON to TS type representing valid store object`
In this particular scenario each address from the server comes in the form: `{address_type: string, address: object}` once validated our TS type: `ValidatedAddressWithTypeJSON` is then converted to its store representation: `Address` which has its type field embedded.
=> Clean up task service implementation

.env.example, App.js, README.md, app.json, package.json, src/@types/sentry-expo.d.ts, src/application/error_boundary.tsx, src/sagas/services.ts, yarn.lock
Service validation errors are now yielded, like http errors, so we get useful error messages from our services saga when validation fails. As it stands we're not currently surfacing these errors but I did look into how to do that with Sentry.
I was able to get it working so our exceptions can be passed from our error boundary over to sentry. Which is pretty neat. This is what it looks like in Sentry when validation fails on a service from our API:
The stack trace is also really nice and we also can assign these errors to people kind of like Github tickets.
Anyways, to actually get this in place we need to do a couple things:
- Set up a Sentry account for Peacegeeks
- Follow the set up here: https://docs.expo.io/versions/latest/guides/using-sentry
- Move our error boundary into App.js. I …
=> Issue #313 Clean up services saga and document Sentry integration

src/components/expandable_content/expandable_content_component.tsx
Android doesn't like "scroll", "hidden" works fine so we'll go with that.
=> Issue #471 Use overflow hidden instead of scroll for read more

src/components/disclaimer/disclaimer_component.tsx
These issues sneak by us because the links work when running the app through Expo but don’t when using a binary. The secret here is to make sure your link components are not rendered in `<Trans>` components (just as we do in the About component). I've confirmed this is fixed by building a binary only for use on the simulator which produces the following in Arabic:
So you see the links are fixed (open your app to see how they're currently broken) but will need translations.
=> Issue #448 Fix disclaimer links

src/components/topics/task_detail_content_component.tsx
Dynamic strings can be translated if they are wrapped with the `<Trans>` macro and added as the `id` prop. 
We have recently introduced a new workflow with our ui-strings where we no longer use the fixtures data to receive translated strings. All translated strings can be found in the in a minified js file - `locale/*/messages.js` which lingui uses to find translated strings. 
I had to remove the capitalization of this category string because I would need to add a version of each category translation in uppercased format IE: 
```
msgid SETTLING IN
msgstr S'INSTALLER
```
As well native-base `<Text>`component currently does not have a way to text-transform this into uppercase like react natives `<Text>` component does.
=> Issue #698 missing explore category translations 

src/components/maps_application_popup/maps_application_popup_component.tsx
This is a NativeBase thing that happens when you nest their Text component inside their Button component, and only on Android, easy fix though.
=> Issue #712 Fix uppercase button text on Android

src/application/styles.ts, src/components/expandable_content/expandable_content_component.tsx, src/components/explore/explore_detail_content_component.tsx, src/components/services/service_list_item_component.tsx, src/components/topics/task_detail_content_component.tsx
Along with the styling outlined in #703 these changes will also address some unwanted padding for the "Read more" component, discussed here: https://github.com/pg-irc/pathways-frontend/issues/663. The issues with cut-off text have been thoroughly discussed and come down to platform specific problems that we don't intend on fixing at this moment.
It may be useful if @cherrielam took a look at this PR as I've had to somewhat improvise on the heading style (although it should seem reasonable).
=> Issue #703 Style markdown component

src/application/styles.ts, src/components/expandable_content/expandable_content_component.tsx, src/components/topics/task_detail_content_component.tsx, src/components/topics/task_list_item_component.tsx
There are 4 changes addressed in this PR:
=> Issue#703 Remaining UI issues related to the markdown/font styling

src/components/swipeable_content/swipeable_content_component.tsx
Well, this was a slog as the documentation is pretty light on this topic. It turns out the fix is quite simple though and has to do with the fact that the onMove gesture responder is very sensitive and tends to highjack events bubbled from buttons so instead we use onStart. The button should work as expected now this has been tested (in Expo) on iPhone X (has 3d touch and works so we don't need our previous 3d touch "fix"), iPhone 8, Android 10, and Android 6.
=> Issue #822 Fix start button for onboarding

src/validation/latlong/index.ts, src/validation/search/index.ts, src/validation/services/__tests__/helpers/services_schema_helpers.ts, src/validation/services/__tests__/services_schema.test.ts, src/validation/services/__tests__/to_human_service_data.test.ts, src/validation/services/index.ts, src/validation/services/schema.ts, src/validation/services/types.ts
`services_at_location_id` has been added as an optional property. The reason it has been made option and not required is because the current Algolia data does not provide the `service_at_location_id`.
=> QA-Tool Issue include services_at_location_id to human service data

src/async/location.ts
As per the documentation: "Consider using Location.getLastKnownPositionAsync if you expect to get a quick response and high accuracy is not required."  (https://docs.expo.io/versions/latest/sdk/location/#locationgetcurrentpositionasyncoptions). We were already setting the mode to low accuracy so I'm hoping this is sufficient and addresses the problems Jean outlines here: https://github.com/pg-irc/pathways-frontend/issues/861#issuecomment-575372732.
Testing instructions here: https://github.com/pg-irc/pathways-frontend/issues/861#issuecomment-583054283.
=> Issue #861 Use last position to improve performance

package.json, yarn.lock
Upgrading ts-node 8.6.2 slows down compilation by a lot. 
https://github.com/TypeStrong/ts-node/issues/754
=> Issue #1006 downgrade ts-node

src/components/bookmark_button/bookmark_button_component.tsx
So I tested this side by side on Android and iOS simulators and I think 2 seconds is a good amount of time for both platforms. However, I'm told that maybe on some physical Android devices the notification popup is too short. Please check and let me know!
=> Issue #1017 Adjust notification time

src/components/search/infinite_hits_component.tsx
When Load more services was clicked, a complete re-render of the infiniteHitsComponent was triggered which would start the search service list from the top. In this PR, I overlaid the LoadingServiceList over top of the service list to prevent this from happening.
=> Issue #1012 clicking load more services keeps scroll position

README.md
- `create-react-native-app` is actually deprecated now so changing it instead to `expo`.
- Replace `redux-first-router` to `react-router-native`
=> Update README to reference expo and react-router-native

src/application/styles.ts, src/components/help/help_component.tsx, src/components/help/help_connected_component.tsx, src/components/help/manual_user_location.tsx, src/components/search/api/fetch_lat_long_from_location.ts, src/components/search/clear_input_button.tsx, src/components/search/search_input_component.tsx, src/components/services/empty_service_list_component.tsx, src/components/services/service_list_component.tsx, src/components/services/service_list_connected_component.tsx, src/components/services/service_list_location_search_component.tsx, src/sagas/services.ts, src/selectors/services/select_manual_user_location.ts, src/selectors/services/to_selector_valid_services_for_topic.ts, src/selectors/services/types.ts, src/stores/__tests__/helpers/services_helpers.ts, src/stores/__tests__/services.test.ts, src/stores/manual_user_location.ts, src/stores/services/actions.ts, src/stores/services/index.ts, src/validation/latlong/types.ts, src/validation/services/types.ts
Please review these points:
- The new services location form sets the existing, but not in use, manual user location store value along with a new label property. This allows us to not have to  change the default behaviours of the services saga which will use the manual user location if it exists.
- Having a fixed header, outside the flatlist, now allows us to simplify our "refresh" logic, we don't need to set a timestamp in order to trigger the refresh
- If location lookup fails from the location form currently it does so silently and manual location is not updated, if this is not sufficient we could add lookup error message to the form 
- I've intentionally sparingly used outside code from the existing search files due to the large refactor that is currently being done for search.
=> Issue #1048 Services manual location

src/components/feedback/feedback_modal_container.tsx
The last commit for feedback screens introduced a bug that causes the final "follow this issue" modal to not pop up, see it here: https://github.com/pg-irc/pathways-frontend/commit/53c8944bd35e0040ce2c1921101c9cf9f5ec69f0#diff-d01f34bbf7fd0cdd2b0c252815a358a9R35. This PR corrects it.
=> Fix typo that causes submission modal to never appear

src/components/services/service_list_location_search_component.tsx
The only change needed here was to not refetch the location if it hadn't changed since the previous search for the topic services screen. This was already being done for the search screen. Both these values are already cached in Redux so there was no need to build anything.
=> Issue #1140 Don't refetch the same location

src/components/feedback/header_component.tsx
If you do not see translated feedback strings follow the Steps for QA for Developers [here](https://github.com/pg-irc/pathways-frontend/issues/1263).
The idea for `flex: 4` comes from this thread: https://github.com/GeekyAnts/NativeBase/issues/567
=> Issue #1263 feedback header cuts off

src/application/styles.ts, src/components/welcome/welcome_component.tsx
This change will only appear on iOS. Android does not allow for styling of the picker.
=> Issue #1473 Change styling of locale picker item
